fh_base_aliases = [
"\\attack{$x$} = @big \\image{attack.svg} $x$ @endlast",
"\\attack = \\image{attack.svg}",
"\\move{$x$} = @big \\image{move.svg} $x$ @endlast",
"\\move = \\image{move.svg}",
"\\heal{$x$} = @big \\image{heal.svg} $x$ @endlast",
"\\heal = \\image{heal.svg}",
"\\shield{$x$} = @big \\image{shield.svg} $x$ @endlast",
"\\shield = \\image{shield.svg}",
"\\retaliate{$x$} = @big \\image{retaliate.svg} $x$ @endlast",
"\\retaliate = \\image{retaliate.svg}",
"\\loot{$x$} = @big \\image{loot.svg} $x$ @endlast",
"\\loot = \\image{loot.svg}",
"\\push{$x$} = @big \\image{push.svg} $x$ @endlast",
"\\push = \\image{push.svg}",
"\\pull{$x$} = @big \\image{pull.svg} $x$ @endlast",
"\\pull = \\image{pull.svg}",

"\\target = \\image{target.svg}",
"\\range = \\image{range.svg}",
"\\pierce = \\image{pierce.svg}",
"\\curse{$x$} = @big \\image{curse.svg} @endlast",
"\\curse = \\image{curse.svg}",

"\\generate{$x$} = @mandatory @big \\image{$x$.svg} @endlast",
"\\loss = @bottomright @mandatory @big \\image{loss.svg} @endlast",
"\\persistent = @bottomright @mandatory @big \\image{persistent.svg} @endlast",
"\\round_bonus = @bottomright @mandatory @big \\image{round_bonus.svg} @endlast",
]